= PHP 8.4 будет поддерживать типы данных введённые в Firebird 4.0
Симонов Денис
v0.5 от 10.00.2024
:doctype: article
:encoding: utf-8
:lang: ru
:icons: font

Предстоящий релиз PHP 8.4, который должен выйти в конце 2024 года, содержит множество новых функций и улучшений, главные из которых обработчики свойств (https://wiki.php.net/rfc/property-hooks[property hooks]) и поддержка HTML5 а расширении DOM.

В настоящее для тестирования доступна версия PHP 8.4 Beta 4.

Разработчикам использующим СУБД Firebird будут интересны новые возможности работы с этой СУБД. 

== Историческая справка

Как известно, начиная с PHP 7.4 основным и единственным драйвером для работы с Firebird являет расширение https://www.php.net/manual/en/ref.pdo-firebird.php[pdo_firebird]. Расширение https://www.php.net/manual/en/ibase.installation.php[Firebird/InterBase] было перемещено в PECL и не поставляется в составе PHP. 

В 2016 году я занимался написанием серии статей по работе с СУБД Firebird из различных языков программирования, которые затем легли в основу https://firebirdsql.org/file/documentation/pdf/ru/firebird-30-developer-guide-ru.pdf[Firebird 3.0 Developer's Guide (Russian)] и https://firebirdsql.org/file/documentation/pdf/en/refdocs/fbdevgd30/firebird-30-developers-guide.pdf[Firebird 3.0 Developer's Guide (English)]. В то время актуальными были PHP 7.0 и Firebird 3.0. В одной из этих статей рассказывалось о том как работать с Firebird из PHP, в ней же проводилось сравнение расширений pdo_firebird и Firebird/InterBase. Там же я отметил, что почти все фреймворки и ORM использовали PDO, поскольку он предоставляет унифицированный интерфейс для работы с различными СУБД. Сам же я практически не использовал pdo_firebird в своих разработках, поскольку в то время оно содержало множество ошибок. Расширение Firebird/InterBase было намного стабильней. Но уже тогда я понимал, что будущее за PDO и надо что-то менять.

Однажды на одном русскоязычном форуме sql.ru была создана тема, в которой обсуждались ошибке в драйвере pdo_firebird, и один из участников форума набрался смелости и исправил несколько ошибок, сделав соответствующие Pull Requests. В эту тему продолжали публиковать сообщения об ошибках с надеждой, что он их исправит. Тогда я решил присоединиться и тоже попробовать, что-то исправить и мне это удалось. Вот краткий перечень того что было исправлено мной:

- утечка памяти при работе с типом данных BLOB;
- поддержка типа данных `BOOLEAN` для входных параметров запросов;
- улучшенный разбор именованных параметров в операторе `EXECUTE BLOCK`.

Поэтому команда разработчиков PHP приняла решение об исключении расширения Firebird/InterBase из состава PHP, я не сильно расстроился. К тому времени расширение pdo_firebird уже стало стабильным, и я с легкостью заменил им расширение Firebird/InterBase.

== Работа с Firebird 4.0 в настоящее время

Как известно в Firebird 4.0 был добавлены новые типы данных:

- `DECFLOAT(16)` и `DECFLOAT(34)`;
- `TIME WITH TIME ZONE` и `TIMESTAMP WITH TIME ZONE`;
- `INT128`, который лежит в основе `NUMERIC(38, x)` и `DECIMAL(38, x)`.

Первые два типа данных не вызывают проблем, они используются редко и предназначены в основном для точных научных вычислений.

С `TIME WITH TIME ZONE` и `TIMESTAMP WITH TIME ZONE` дела обстоят сложнее. Дело в том, что до введения этих типов данных контекстные переменные `CURRENT_TIME` и `CURRENT_TIMESTAMP` возвращали значения типов `TIME WITHOUT TIME ZONE` и `TIMESTAMP WITHOUT TIME ZONE`, хотя это противоречило стандарту SQL, теперь же они возвращают `TIME WITH TIME ZONE` и `TIMESTAMP WITH TIME ZONE`. Для возврата значений без информации о часовых поясах предусмотрены контекстные переменные `LOCALTIME` и `LOCALTIMESTAMP`. Поэтому те запросы, которые раньше работали корректно возвращают новые типы данных, которые неизвестны драйверу pdo_firebird.
